local BattleLogic = require("BattleLogic")
require("BattleData")
local function main()
  local c = BattleLogic:new()
  local hero1 = {id = 1,static_id = 1001,level = 10,career = 1,exeunt = {scene = 1,debut = 3},cur_anger = 100,cur_hp = 10000,attr = {[ATTRTYPE.HP] = 10000,[ATTRTYPE.VIOLEVEL] = 1,[ATTRTYPE.SPEED] = 20,[ATTRTYPE.SECOND_ACTION] = 0,[ATTRTYPE.ANGER] = 8,[ATTRTYPE.WULI_ATTACK] = 30,[ATTRTYPE.MOFA_ATTACK] = 1000,[ATTRTYPE.WULI_DEFEND] = 20,[ATTRTYPE.MOFA_DEFEND] = 18,[ATTRTYPE.BAOJI_LEVEL] = 1,[ATTRTYPE.BAOJIHURT_ADDON_RATE] = 1,[ATTRTYPE.MINGZHONG_LEVEL] = 1,[ATTRTYPE.SHANGBI_LEVEL] = 1,[ATTRTYPE.GEDANG_LEVEL] = 1,[ATTRTYPE.RANGXING_RATE] = 1,[ATTRTYPE.HURT_ADDON_RATE] = 1,[ATTRTYPE.HURT_REDUCE_RATE] = 1,[ATTRTYPE.PVP_HURTADDON] = 0,[ATTRTYPE.PVP_HURTREDUCE] = 0 ,[ATTRTYPE.RECOVERY] = 1,[ATTRTYPE.SUPERSKILL_RATE] = 50,[ATTRTYPE.CUREUP] = 100},normal_skill = {skill_id = 601201,skill_level = 1},s_skill = {skill_id = 601304,skill_level = 1},f_skill = {skill_id = 603103,skill_level = 1}}
  local hero2 = {id = 2,level = 10,cur_anger = 100,career = 1,cur_hp = 10000,attr = {[ATTRTYPE.HP] = 30000,[ATTRTYPE.VIOLEVEL] = 1,[ATTRTYPE.SPEED] = 30,[ATTRTYPE.SECOND_ACTION] = 1,[ATTRTYPE.ANGER] = 1,[ATTRTYPE.WULI_ATTACK] = 24,[ATTRTYPE.MOFA_ATTACK] = 13,[ATTRTYPE.WULI_DEFEND] = 10,[ATTRTYPE.MOFA_DEFEND] = 20,[ATTRTYPE.BAOJI_LEVEL] = 1,[ATTRTYPE.BAOJIHURT_ADDON_RATE] = 1,[ATTRTYPE.MINGZHONG_LEVEL] = 1,[ATTRTYPE.SHANGBI_LEVEL] = 1,[ATTRTYPE.GEDANG_LEVEL] = 1,[ATTRTYPE.RANGXING_RATE] = 1,[ATTRTYPE.HURT_ADDON_RATE] = 1,[ATTRTYPE.HURT_REDUCE_RATE] = 1,[ATTRTYPE.RECOVERY] = 1,[ATTRTYPE.SUPERSKILL_RATE] = 50,[ATTRTYPE.PVP_HURTADDON] = 0,[ATTRTYPE.PVP_HURTREDUCE] = 0,[ATTRTYPE.CUREUP] = 100},normal_skill = {skill_id = 600406,skill_level = 100},skills = {{skill_id = 603103,skill_level = 100},{skill_id = 603103,skill_level = 100}},s_skill= {skill_id = 601304,skill_level = 100}}
  local hero9 = {id = 3,level = 10,cur_anger = 100,career = 1,cur_hp = 10000,attr = {[ATTRTYPE.HP] = 30000,[ATTRTYPE.VIOLEVEL] = 1,[ATTRTYPE.SPEED] = 30,[ATTRTYPE.SECOND_ACTION] = 1,[ATTRTYPE.ANGER] = 1,[ATTRTYPE.WULI_ATTACK] = 24,[ATTRTYPE.MOFA_ATTACK] = 13,[ATTRTYPE.WULI_DEFEND] = 20,[ATTRTYPE.MOFA_DEFEND] = 20,[ATTRTYPE.BAOJI_LEVEL] = 1,[ATTRTYPE.BAOJIHURT_ADDON_RATE] = 1,[ATTRTYPE.MINGZHONG_LEVEL] = 1,[ATTRTYPE.SHANGBI_LEVEL] = 1,[ATTRTYPE.GEDANG_LEVEL] = 1,[ATTRTYPE.RANGXING_RATE] = 1,[ATTRTYPE.HURT_ADDON_RATE] = 1,[ATTRTYPE.HURT_REDUCE_RATE] = 1,[ATTRTYPE.RECOVERY] = 1,[ATTRTYPE.SUPERSKILL_RATE] = 50,[ATTRTYPE.PVP_HURTADDON] = 0,[ATTRTYPE.PVP_HURTREDUCE] = 0,[ATTRTYPE.CUREUP] = 100},normal_skill = {skill_id = 601201,skill_level = 1},skills = {{skill_id = 603103,skill_level = 1},{skill_id = 603103,skill_level = 1}},s_skill= {skill_id = 601304,skill_level = 1},f_skill = {skill_id = 600501,skill_level = 1}}
  local hero10 = {id = 4,level = 10,cur_anger = 100,career = 1,cur_hp = 10000,attr = {[ATTRTYPE.HP] = 30000,[ATTRTYPE.VIOLEVEL] = 1,[ATTRTYPE.SPEED] = 30,[ATTRTYPE.SECOND_ACTION] = 1,[ATTRTYPE.ANGER] = 1,[ATTRTYPE.WULI_ATTACK] = 24,[ATTRTYPE.MOFA_ATTACK] = 13,[ATTRTYPE.WULI_DEFEND] = 10,[ATTRTYPE.MOFA_DEFEND] = 20,[ATTRTYPE.BAOJI_LEVEL] = 1,[ATTRTYPE.BAOJIHURT_ADDON_RATE] = 1,[ATTRTYPE.MINGZHONG_LEVEL] = 1,[ATTRTYPE.SHANGBI_LEVEL] = 1,[ATTRTYPE.GEDANG_LEVEL] = 1,[ATTRTYPE.RANGXING_RATE] = 1,[ATTRTYPE.HURT_ADDON_RATE] = 1,[ATTRTYPE.HURT_REDUCE_RATE] = 1,[ATTRTYPE.RECOVERY] = 1,[ATTRTYPE.SUPERSKILL_RATE] = 50,[ATTRTYPE.PVP_HURTADDON] = 0,[ATTRTYPE.PVP_HURTREDUCE] = 0,[ATTRTYPE.CUREUP] = 100},normal_skill = {skill_id = 601201,skill_level = 1},skills = {{skill_id = 603103,skill_level = 1},{skill_id = 603103,skill_level = 1}},s_skill= {skill_id = 601304,skill_level = 1},f_skill = {skill_id = 600501,skill_level = 1}}
  local hero11 = {id = 5,level = 10,cur_anger = 100,career = 1,cur_hp = 10000,attr = {[ATTRTYPE.HP] = 30000,[ATTRTYPE.VIOLEVEL] = 1,[ATTRTYPE.SPEED] = 30,[ATTRTYPE.SECOND_ACTION] = 1,[ATTRTYPE.ANGER] = 1,[ATTRTYPE.WULI_ATTACK] = 24,[ATTRTYPE.MOFA_ATTACK] = 13,[ATTRTYPE.WULI_DEFEND] = 80,[ATTRTYPE.MOFA_DEFEND] = 20,[ATTRTYPE.BAOJI_LEVEL] = 1,[ATTRTYPE.BAOJIHURT_ADDON_RATE] = 1,[ATTRTYPE.MINGZHONG_LEVEL] = 1,[ATTRTYPE.SHANGBI_LEVEL] = 1,[ATTRTYPE.GEDANG_LEVEL] = 1,[ATTRTYPE.RANGXING_RATE] = 1,[ATTRTYPE.HURT_ADDON_RATE] = 1,[ATTRTYPE.HURT_REDUCE_RATE] = 1,[ATTRTYPE.RECOVERY] = 1,[ATTRTYPE.SUPERSKILL_RATE] = 50,[ATTRTYPE.PVP_HURTADDON] = 0,[ATTRTYPE.PVP_HURTREDUCE] = 0,[ATTRTYPE.CUREUP] = 100},normal_skill = {skill_id = 601201,skill_level = 1},skills = {{skill_id = 603103,skill_level = 1},{skill_id = 603103,skill_level = 1}},s_skill= {skill_id = 601304,skill_level = 1},f_skill = {skill_id = 600501,skill_level = 1}}
  local hero12 = {id = 6,level = 10,cur_anger = 100,career = 1,cur_hp = 10000,attr = {[ATTRTYPE.HP] = 30000,[ATTRTYPE.VIOLEVEL] = 1,[ATTRTYPE.SPEED] = 30,[ATTRTYPE.SECOND_ACTION] = 1,[ATTRTYPE.ANGER] = 1,[ATTRTYPE.WULI_ATTACK] = 24,[ATTRTYPE.MOFA_ATTACK] = 13,[ATTRTYPE.WULI_DEFEND] = 20,[ATTRTYPE.MOFA_DEFEND] = 20,[ATTRTYPE.BAOJI_LEVEL] = 1,[ATTRTYPE.BAOJIHURT_ADDON_RATE] = 1,[ATTRTYPE.MINGZHONG_LEVEL] = 1,[ATTRTYPE.SHANGBI_LEVEL] = 1,[ATTRTYPE.GEDANG_LEVEL] = 1,[ATTRTYPE.RANGXING_RATE] = 1,[ATTRTYPE.HURT_ADDON_RATE] = 1,[ATTRTYPE.HURT_REDUCE_RATE] = 1,[ATTRTYPE.RECOVERY] = 1,[ATTRTYPE.SUPERSKILL_RATE] = 50,[ATTRTYPE.PVP_HURTADDON] = 0,[ATTRTYPE.PVP_HURTREDUCE] = 0,[ATTRTYPE.CUREUP] = 100},normal_skill = {skill_id = 601201,skill_level = 1},skills = {{skill_id = 603103,skill_level = 1},{skill_id = 603103,skill_level = 1}},s_skill= {skill_id = 601304,skill_level = 1},f_skill = {skill_id = 600501,skill_level = 1}}
  local hero13 = {id = 2,level = 10,cur_anger = 100,career = 1,cur_hp = 10000,attr = {[ATTRTYPE.HP] = 30000,[ATTRTYPE.VIOLEVEL] = 1,[ATTRTYPE.SPEED] = 30,[ATTRTYPE.SECOND_ACTION] = 1,[ATTRTYPE.ANGER] = 1,[ATTRTYPE.WULI_ATTACK] = 24,[ATTRTYPE.MOFA_ATTACK] = 13,[ATTRTYPE.WULI_DEFEND] = 40,[ATTRTYPE.MOFA_DEFEND] = 20,[ATTRTYPE.BAOJI_LEVEL] = 1,[ATTRTYPE.BAOJIHURT_ADDON_RATE] = 1,[ATTRTYPE.MINGZHONG_LEVEL] = 1,[ATTRTYPE.SHANGBI_LEVEL] = 1,[ATTRTYPE.GEDANG_LEVEL] = 1,[ATTRTYPE.RANGXING_RATE] = 1,[ATTRTYPE.HURT_ADDON_RATE] = 1,[ATTRTYPE.HURT_REDUCE_RATE] = 1,[ATTRTYPE.RECOVERY] = 1,[ATTRTYPE.SUPERSKILL_RATE] = 50,[ATTRTYPE.PVP_HURTADDON] = 0,[ATTRTYPE.PVP_HURTREDUCE] = 0,[ATTRTYPE.CUREUP] = 100},normal_skill = {skill_id = 601201,skill_level = 1},skills = {{skill_id = 603103,skill_level = 1},{skill_id = 603103,skill_level = 1}},s_skill= {skill_id = 601304,skill_level = 1},f_skill = {skill_id = 600501,skill_level = 1}}
  local hero3 = {id = 1,level = 6,cur_anger = 100,career = 1,cur_hp = 10000,--[[sky = {scene = 1,debut = 3},]]attr = {[ATTRTYPE.HP] = 3000,[ATTRTYPE.VIOLEVEL] = 1,[ATTRTYPE.SPEED] = 25,[ATTRTYPE.SECOND_ACTION] = 1,[ATTRTYPE.ANGER] = 1,[ATTRTYPE.WULI_ATTACK] = 40,[ATTRTYPE.MOFA_ATTACK] = 30,[ATTRTYPE.WULI_DEFEND] = 10,[ATTRTYPE.MOFA_DEFEND] = 40,[ATTRTYPE.BAOJI_LEVEL] = 1,[ATTRTYPE.BAOJIHURT_ADDON_RATE] = 1,[ATTRTYPE.MINGZHONG_LEVEL] = 1,[ATTRTYPE.SHANGBI_LEVEL] = 1,[ATTRTYPE.GEDANG_LEVEL] = 1,[ATTRTYPE.RANGXING_RATE] = 1,[ATTRTYPE.HURT_ADDON_RATE] = 1,[ATTRTYPE.HURT_REDUCE_RATE] = 1,[ATTRTYPE.RECOVERY] = 1,[ATTRTYPE.SUPERSKILL_RATE] = 50,[ATTRTYPE.PVP_HURTADDON] = 0,[ATTRTYPE.PVP_HURTREDUCE] = 0,[ATTRTYPE.CUREUP] = 100},normal_skill = {skill_id = 601201,skill_level = 1},skills = {},s_skill= {skill_id = 601304,skill_level = 1},f_skill = {skill_id = 600501,skill_level = 1}} 
  local hero4 = {id = 2,level = 10,cur_anger = 100,career = 1,cur_hp = 10000,attr = {[ATTRTYPE.HP] = 10000,[ATTRTYPE.VIOLEVEL] = 1,[ATTRTYPE.SPEED] = 18,[ATTRTYPE.SECOND_ACTION] = 0,[ATTRTYPE.ANGER] = 1,[ATTRTYPE.WULI_ATTACK] = 41,[ATTRTYPE.MOFA_ATTACK] = 26,[ATTRTYPE.WULI_DEFEND] = 5,[ATTRTYPE.MOFA_DEFEND] = 41,[ATTRTYPE.BAOJI_LEVEL] = 1,[ATTRTYPE.BAOJIHURT_ADDON_RATE] = 1,[ATTRTYPE.MINGZHONG_LEVEL] = 1,[ATTRTYPE.SHANGBI_LEVEL] = 1,[ATTRTYPE.GEDANG_LEVEL] = 1,[ATTRTYPE.RANGXING_RATE] = 1,[ATTRTYPE.HURT_ADDON_RATE] = 1,[ATTRTYPE.HURT_REDUCE_RATE] = 1,[ATTRTYPE.RECOVERY] = 1,[ATTRTYPE.SUPERSKILL_RATE] = 50,[ATTRTYPE.PVP_HURTADDON] = 0,[ATTRTYPE.PVP_HURTREDUCE] = 0,[ATTRTYPE.CUREUP] = 100},normal_skill = {skill_id = 601201,skill_level = 1},skills = {{skill_id = 603103,skill_level = 1},{skill_id = 603103,skill_level = 1}},s_skill= {skill_id = 601304,skill_level = 1},f_skill = {skill_id = 600501,skill_level = 1}} 
  local hero5 = {id = 3,level = 10,cur_anger = 100,career = 1,cur_hp = 10000,attr = {[ATTRTYPE.HP] = 10000,[ATTRTYPE.VIOLEVEL] = 1,[ATTRTYPE.SPEED] = 25,[ATTRTYPE.SECOND_ACTION] = 1,[ATTRTYPE.ANGER] = 1,[ATTRTYPE.WULI_ATTACK] = 42,[ATTRTYPE.MOFA_ATTACK] = 22,[ATTRTYPE.WULI_DEFEND] = 15,[ATTRTYPE.MOFA_DEFEND] = 42,[ATTRTYPE.BAOJI_LEVEL] = 1,[ATTRTYPE.BAOJIHURT_ADDON_RATE] = 1,[ATTRTYPE.MINGZHONG_LEVEL] = 1,[ATTRTYPE.SHANGBI_LEVEL] = 1,[ATTRTYPE.GEDANG_LEVEL] = 1,[ATTRTYPE.RANGXING_RATE] = 1,[ATTRTYPE.HURT_ADDON_RATE] = 1,[ATTRTYPE.HURT_REDUCE_RATE] = 1,[ATTRTYPE.RECOVERY] = 1,[ATTRTYPE.SUPERSKILL_RATE] = 50,[ATTRTYPE.PVP_HURTADDON] = 0,[ATTRTYPE.PVP_HURTREDUCE] = 0,[ATTRTYPE.CUREUP] = 100},normal_skill = {skill_id = 601201,skill_level = 1},skills = {{skill_id = 603103,skill_level = 1},{skill_id = 603103,skill_level = 1}},s_skill= {skill_id = 601304,skill_level = 1},f_skill = {skill_id = 600501,skill_level = 1}} 
  local hero6 = {id = 4,level = 10,cur_anger = 100,career = 1,cur_hp = 10000,attr = {[ATTRTYPE.HP] = 10000,[ATTRTYPE.VIOLEVEL] = 1,[ATTRTYPE.SPEED] = 18,[ATTRTYPE.SECOND_ACTION] = 0,[ATTRTYPE.ANGER] = 1,[ATTRTYPE.WULI_ATTACK] = 43,[ATTRTYPE.MOFA_ATTACK] = 20,[ATTRTYPE.WULI_DEFEND] = 18,[ATTRTYPE.MOFA_DEFEND] = 49,[ATTRTYPE.BAOJI_LEVEL] = 1,[ATTRTYPE.BAOJIHURT_ADDON_RATE] = 1,[ATTRTYPE.MINGZHONG_LEVEL] = 1,[ATTRTYPE.SHANGBI_LEVEL] = 1,[ATTRTYPE.GEDANG_LEVEL] = 1,[ATTRTYPE.RANGXING_RATE] = 1,[ATTRTYPE.HURT_ADDON_RATE] = 1,[ATTRTYPE.HURT_REDUCE_RATE] = 1,[ATTRTYPE.RECOVERY] = 1,[ATTRTYPE.SUPERSKILL_RATE] = 50,[ATTRTYPE.PVP_HURTADDON] = 0,[ATTRTYPE.PVP_HURTREDUCE] = 0,[ATTRTYPE.CUREUP] = 100},normal_skill = {skill_id = 601201,skill_level = 1},skills = {{skill_id = 603103,skill_level = 1},{skill_id = 603103,skill_level = 1}},s_skill= {skill_id = 601304,skill_level = 1},f_skill = {skill_id = 600501,skill_level = 1}}                              
  local hero7 = {id = 5,level = 10,cur_anger = 100,career = 1,cur_hp = 10000,attr = {[ATTRTYPE.HP] = 10000,[ATTRTYPE.VIOLEVEL] = 1,[ATTRTYPE.SPEED] = 25,[ATTRTYPE.SECOND_ACTION] = 1,[ATTRTYPE.ANGER] = 1,[ATTRTYPE.WULI_ATTACK] = 44,[ATTRTYPE.MOFA_ATTACK] = 17,[ATTRTYPE.WULI_DEFEND] = 20,[ATTRTYPE.MOFA_DEFEND] = 48,[ATTRTYPE.BAOJI_LEVEL] = 1,[ATTRTYPE.BAOJIHURT_ADDON_RATE] = 1,[ATTRTYPE.MINGZHONG_LEVEL] = 1,[ATTRTYPE.SHANGBI_LEVEL] = 1,[ATTRTYPE.GEDANG_LEVEL] = 1,[ATTRTYPE.RANGXING_RATE] = 1,[ATTRTYPE.HURT_ADDON_RATE] = 1,[ATTRTYPE.HURT_REDUCE_RATE] = 1,[ATTRTYPE.RECOVERY] = 1,[ATTRTYPE.SUPERSKILL_RATE] = 50,[ATTRTYPE.PVP_HURTADDON] = 0,[ATTRTYPE.PVP_HURTREDUCE] = 0,[ATTRTYPE.CUREUP] = 100},normal_skill = {skill_id = 601201,skill_level = 1},skills = {{skill_id = 603103,skill_level = 1},{skill_id = 603103,skill_level = 1}},s_skill= {skill_id = 601304,skill_level = 1},f_skill = {skill_id = 600501,skill_level = 1}} 
  local hero8 = {id = 6,level = 10,cur_anger = 500,career = 1,cur_hp = 10000,boss = {boss_hp_strip = 30},attr = {[ATTRTYPE.HP] = 500,[ATTRTYPE.VIOLEVEL] = 1,[ATTRTYPE.SPEED] = 18,[ATTRTYPE.SECOND_ACTION] = 0,[ATTRTYPE.ANGER] = 1,[ATTRTYPE.WULI_ATTACK] = 45,[ATTRTYPE.MOFA_ATTACK] = 19,[ATTRTYPE.WULI_DEFEND] = 23,[ATTRTYPE.MOFA_DEFEND] = 47,[ATTRTYPE.BAOJI_LEVEL] = 1,[ATTRTYPE.BAOJIHURT_ADDON_RATE] = 1,[ATTRTYPE.MINGZHONG_LEVEL] = 1,[ATTRTYPE.SHANGBI_LEVEL] = 1,[ATTRTYPE.GEDANG_LEVEL] = 1,[ATTRTYPE.RANGXING_RATE] = 1,[ATTRTYPE.HURT_ADDON_RATE] = 1,[ATTRTYPE.HURT_REDUCE_RATE] = 1,[ATTRTYPE.RECOVERY] = 1,[ATTRTYPE.SUPERSKILL_RATE] = 50,[ATTRTYPE.PVP_HURTADDON] = 0,[ATTRTYPE.PVP_HURTREDUCE] = 0,[ATTRTYPE.CUREUP] = 100},normal_skill = {skill_id = 601201,skill_level = 1},skills = {{skill_id = 603103,skill_level = 1},{skill_id = 603103,skill_level = 1}},s_skill= {skill_id = 601304,skill_level = 1},f_skill = {skill_id = 600501,skill_level = 1}}                              
  local master1 = {link = 5,normal_skill = {skill_id = 601202,skill_level = 1},curse = {skill_id = 601201,skill_level = 1}}--和谁联结，普通技能，令咒
  local master2 = {link = 0,normal_skill = {skill_id = 601202,skill_level = 1},curse = {skill_id = 601201,skill_level = 1}}
  local our = {}
  local peer = {}
  table.insert(our,hero3)
  --table.insert(our,hero2)
  --table.insert(our,hero9)
  --table.insert(our,hero10)
  --table.insert(our,hero11)
  --table.insert(our,hero12)
  table.insert(peer,hero1)
  table.insert(peer,hero4)
  table.insert(peer,hero5)
  table.insert(peer,hero6)
  table.insert(peer,hero7)
  table.insert(peer,hero8)
  c:LogSwitch("","a.txt")
  c:InitBattle(our,master1,peer,nil,FIGHTTYPE.AUTO,334,FIGHTMODE.MODE1)
  local result = FIGHTRESULT.PASS
  local i = 0
  while(result == FIGHTRESULT.PASS)
    do
    result = c:Update()-----------------运行一次产生数据
    --c:GetFightDatas() ----------------取数据表现
    --c:ShowFightDataVec()
    --sleep(5)
    i = i + 1
    --print("count = ".. i)
  end
  print("result = " .. result)
  c:PrintStatNum()
  ffile = io.open("1.txt","w")
  ffile:write(c:GetAllLog())
end
main()

